# Generated by Django 5.1.7 on 2026-04-26 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="username",
            name="phrase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="names",
                to="core.phrase",
            ),
        ),
        migrations.AddField(
            model_name="username",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="names",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
