# Generated by Django 6.0.4 on 2026-08-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="username",
            name="phrase",
        ),
    ]
