# Generated by Django 5.1.7 on 2026-04-18 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('language', models.CharField(max_length=3)),
                ('translation', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('given_name', 'Given Name'), ('family_name', 'Family Name'), ('nasab_name', 'Nasab'), ('nick_name', 'Nick Name'), ('title_name', 'Title'), ('laqab_name', 'Laqab'), ('kunyah_name', 'Kunyah'), ('nisbah_name', 'Nisbah')], default='given_name', max_length=16)),
                ('text', models.TextField()),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
