# Generated by Django 5.1.7 on 2026-04-20 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_username_user'),
        ('core', '0014_delete_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username',
            name='translation',
        ),
        migrations.AddField(
            model_name='username',
            name='phrase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='core.phrase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='username',
            name='type',
            field=models.CharField(choices=[('given_name', 'Given Name'), ('family_name', 'Family Name'), ('nasab_name', 'Nasab'), ('nick_name', 'Nick Name'), ('title_name', 'Title'), ('laqab_name', 'Laqab'), ('kunyah_name', 'Kunyah'), ('nisbah_name', 'Nisbah')], max_length=16),
        ),
    ]
