# Generated by Django 5.1.7 on 2026-04-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_username_translation_username_phrase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='is_primary',
            field=models.BooleanField(),
        ),
    ]
