# Generated by Django 5.1.7 on 2026-04-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorlog",
            name="extra_context",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
