# Generated by Django 5.1.7 on 2026-04-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_errorlog_extra_context"),
    ]

    operations = [
        migrations.RenameField(
            model_name="errorlog",
            old_name="request_action",
            new_name="request_method",
        ),
    ]
