# Generated by Django 5.1.7 on 2026-04-29 11:10

import core.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_request_action_errorlog_request_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=core.expressions.UUIDv7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("status_code", models.IntegerField()),
                ("response_data", models.TextField()),
                ("detail", models.TextField(blank=True, null=True)),
                ("account_id", models.IntegerField(blank=True, null=True)),
                ("token", models.CharField(blank=True, max_length=64, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("ipv4", models.TextField()),
                ("url", models.TextField(blank=True, null=True)),
                ("controller", models.TextField(blank=True, null=True)),
                ("method", models.TextField(blank=True, null=True)),
                ("response_body", models.BinaryField(blank=True, null=True)),
                ("response_body_content_type", models.TextField(blank=True, null=True)),
                ("extra_context", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.DeleteModel(
            name="ErrorLog",
        ),
    ]
