# Generated by Django 6.0.4 on 2026-08-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_username_phrase"),
        ("core", "0005_alter_phrasevalues_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phrasevalues",
            name="phrase",
        ),
        migrations.RemoveField(
            model_name="phrasevalues",
            name="creator",
        ),
        migrations.DeleteModel(
            name="Phrase",
        ),
        migrations.DeleteModel(
            name="PhraseValues",
        ),
    ]
