# Generated by Django 5.1.7 on 2026-04-14 09:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_update_language_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('language', models.CharField(max_length=3)),
                ('translation', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('first_name', 'First Name'), ('last_name', 'Last Name'), ('parent_name', 'Parent Name'), ('nick_name', 'Nick Name'), ('title_name', 'Title'), ('laqab_name', 'Laqab'), ('kunyah_name', 'Kunyah')], default='first_name', max_length=16)),
                ('text', models.TextField()),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
