# Generated by Django 5.1.7 on 2026-04-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='type',
            field=models.CharField(choices=[('given_name', 'Given Name'), ('family_name', 'Family Name'), ('nasab_name', 'Nasab'), ('nick_name', 'Nick Name'), ('title_name', 'Title'), ('laqab_name', 'Laqab'), ('kunyah_name', 'Kunyah'), ('nisbah_name', 'Nisbah')], default='given_name', max_length=16),
        ),
    ]
