# Generated by Django 5.1.7 on 2026-04-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_username_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserName',
        ),
    ]
