/* tslint:disable */
/* eslint-disable */
/**
 * Natiq API
 * Natiq Quran API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



// Export API classes directly to avoid enum conflicts
export { AuthApi } from './api/auth-api';
export { AyahsApi } from './api/ayahs-api';
export { GeneralApi } from './api/general-api';
export { GroupsApi } from './api/groups-api';
export { HealthApi } from './api/health-api';
export { MushafsApi } from './api/mushafs-api';
export { NotificationsApi } from './api/notifications-api';
export { PhrasesApi } from './api/phrases-api';
export { ProfileApi } from './api/profile-api';
export { RecitationsApi } from './api/recitations-api';
export { SurahsApi } from './api/surahs-api';
export { TakhtitsApi } from './api/takhtits-api';
export { TranslationsApi } from './api/translations-api';
export { UsersApi } from './api/users-api';
export { WordsApi } from './api/words-api';

