/* tslint:disable */
/* eslint-disable */
/**
 * Natiq API
 * Natiq Quran API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AyahAdd {
    'surah_uuid': string;
    'text': string;
    'is_bismillah'?: boolean;
    'bismillah_text'?: string | null;
    'sajdah'?: string | null;
}

