/* tslint:disable */
/* eslint-disable */
/**
 * Natiq API
 * Natiq Quran API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AyahBreaker {
    'uuid': string;
    /**
     * * `page` - Page * `juz` - Juz * `hizb` - Hizb * `rub` - Rub * `manzil` - Manzil * `ruku` - Ruku
     */
    'type': AyahBreakerTypeEnum;
}

export const AyahBreakerTypeEnum = {
    Page: 'page',
    Juz: 'juz',
    Hizb: 'hizb',
    Rub: 'rub',
    Manzil: 'manzil',
    Ruku: 'ruku'
} as const;

export type AyahBreakerTypeEnum = typeof AyahBreakerTypeEnum[keyof typeof AyahBreakerTypeEnum];


