/* tslint:disable */
/* eslint-disable */
/**
 * Natiq API
 * Natiq Quran API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface HealthCheckResponse {
    /**
     * Overall health status: healthy, degraded, or unhealthy
     */
    'status': string;
    /**
     * Detailed status of individual services
     */
    'services'?: { [key: string]: { [key: string]: string; }; };
}

