/* tslint:disable */
/* eslint-disable */
/**
 * Natiq API
 * Natiq Quran API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PatchedMushaf {
    'uuid'?: string;
    'short_name'?: string;
    'name'?: string;
    'source'?: string;
    /**
     * * `draft` - Draft * `pending_review` - Pending review * `published` - Published
     */
    'status'?: PatchedMushafStatusEnum;
}

export const PatchedMushafStatusEnum = {
    Draft: 'draft',
    PendingReview: 'pending_review',
    Published: 'published'
} as const;

export type PatchedMushafStatusEnum = typeof PatchedMushafStatusEnum[keyof typeof PatchedMushafStatusEnum];


