/* tslint:disable */
/* eslint-disable */
/**
 * Natiq API
 * Natiq Quran API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PatchedAyah {
    'uuid'?: string;
    'number'?: number;
    /**
     * * `none` - None
     */
    'sajdah'?: PatchedAyahSajdahEnum | null;
    'text'?: string;
    'breakers'?: string;
    'bismillah'?: string;
    'surah'?: string;
}

export const PatchedAyahSajdahEnum = {
    None: 'none'
} as const;

export type PatchedAyahSajdahEnum = typeof PatchedAyahSajdahEnum[keyof typeof PatchedAyahSajdahEnum];


