/* tslint:disable */
/* eslint-disable */
/**
 * Natiq API
 * Natiq Quran API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Translation {
    'uuid': string;
    'mushaf_uuid': string;
    'translator_uuid': string;
    /**
     * * `ar` - ar * `en` - en * `fr` - fr * `ur` - ur * `tr` - tr * `id` - id * `fa` - fa * `ru` - ru * `es` - es * `de` - de * `bn` - bn * `zh` - zh * `ms` - ms * `hi` - hi * `sw` - sw * `ps` - ps * `ku` - ku * `az` - az * `ha` - ha * `so` - so * `ta` - ta * `te` - te * `ml` - ml * `pa` - pa * `sd` - sd * `ug` - ug * `uz` - uz * `kk` - kk * `ky` - ky * `tk` - tk * `tg` - tg * `syr` - syr * `ber` - ber * `am` - am * `om` - om * `wo` - wo * `yo` - yo * `other` - other
     */
    'language': TranslationLanguageEnum;
    'release_date'?: string | null;
    'source'?: string | null;
    /**
     * * `draft` - Draft * `pending_review` - Pending review * `published` - Published
     */
    'status'?: TranslationStatusEnum;
}

export const TranslationLanguageEnum = {
    Ar: 'ar',
    En: 'en',
    Fr: 'fr',
    Ur: 'ur',
    Tr: 'tr',
    Id: 'id',
    Fa: 'fa',
    Ru: 'ru',
    Es: 'es',
    De: 'de',
    Bn: 'bn',
    Zh: 'zh',
    Ms: 'ms',
    Hi: 'hi',
    Sw: 'sw',
    Ps: 'ps',
    Ku: 'ku',
    Az: 'az',
    Ha: 'ha',
    So: 'so',
    Ta: 'ta',
    Te: 'te',
    Ml: 'ml',
    Pa: 'pa',
    Sd: 'sd',
    Ug: 'ug',
    Uz: 'uz',
    Kk: 'kk',
    Ky: 'ky',
    Tk: 'tk',
    Tg: 'tg',
    Syr: 'syr',
    Ber: 'ber',
    Am: 'am',
    Om: 'om',
    Wo: 'wo',
    Yo: 'yo',
    Other: 'other'
} as const;

export type TranslationLanguageEnum = typeof TranslationLanguageEnum[keyof typeof TranslationLanguageEnum];
export const TranslationStatusEnum = {
    Draft: 'draft',
    PendingReview: 'pending_review',
    Published: 'published'
} as const;

export type TranslationStatusEnum = typeof TranslationStatusEnum[keyof typeof TranslationStatusEnum];


