# Generated by Django 5.1.7 on 2026-04-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
