# Generated by Django 5.1.7 on 2026-04-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ayah',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='ayahbreaker',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='ayahtranslation',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='mushaf',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='provenance',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='recitation',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='recitationsurah',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='recitationsurahtimestamp',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='surah',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='surahname',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='takhtit',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='wordbreaker',
            old_name='uuid',
            new_name='id',
        ),
    ]
