# Generated by Django 5.1.7 on 2026-04-11 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provenance',
            name='child_provenance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_provenance', to='quran.provenance'),
        ),
    ]
