# Generated by Django 5.1.7 on 2026-04-11 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_alter_provenance_child_provenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provenance',
            name='child_provenance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_provenance', to='quran.provenance'),
        ),
    ]
