# Generated by Django 6.0.4 on 2026-07-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0003_remove_mushaf_short_name_mushaf_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ayah",
            name="bismillah_text",
        ),
        migrations.AddField(
            model_name="surah",
            name="bismillah_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surah",
            name="has_bismillah",
            field=models.BooleanField(default=True),
        ),
    ]
