# Generated by Django 6.0.4 on 2026-07-08 11:18

import core.expressions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0004_remove_ayah_bismillah_text_surah_bismillah_text_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recitation",
            name="mushaf",
        ),
        migrations.RemoveField(
            model_name="takhtit",
            name="mushaf",
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together={("translator", "language")},
        ),
        migrations.CreateModel(
            name="RasmOlMushaf",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=core.expressions.UUIDv7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("slug", models.CharField(max_length=50, unique=True)),
                ("name", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending review"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collector_rasmOlMushaf",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compiler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compiler_rasmOlMushaf",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mushafs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="surah",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="surah",
            name="rasm_ol_mushaf",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surahs",
                to="quran.rasmolmushaf",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="takhtit",
            name="rasm_ol_mushaf",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="takhtits",
                to="quran.rasmolmushaf",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="surah",
            unique_together={("rasm_ol_mushaf", "number")},
        ),
        migrations.CreateModel(
            name="Transmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=core.expressions.UUIDv7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.TextField()),
                (
                    "provenances",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Transmission",
                        to="quran.provenance",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recitation",
            name="transmission",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recitations",
                to="quran.transmission",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="translation",
            name="transmission",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="quran.transmission",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="translation",
            name="mushaf",
        ),
        migrations.RemoveField(
            model_name="surah",
            name="mushaf",
        ),
        migrations.DeleteModel(
            name="Mushaf",
        ),
    ]
