# Generated by Django 6.0.4 on 2026-07-13 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0005_remove_recitation_mushaf_remove_takhtit_mushaf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transmission",
            name="rasm_ol_mushaf",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transmission",
                to="quran.rasmolmushaf",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transmission",
            name="provenances",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transmission",
                to="quran.provenance",
            ),
        ),
    ]
