# Generated by Django 5.1.7 on 2025-09-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0006_remove_wordbreaker_name_wordbreaker_takhtit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayah',
            name='length',
            field=models.IntegerField(default=0, help_text='Character count of the ayah text (joined words)'),
        ),
    ]
