# Generated by Django 6.0.4 on 2026-07-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0006_transmission_rasm_ol_mushaf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transmission",
            name="slug",
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
