# Generated by Django 6.0.4 on 2026-07-13 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0007_transmission_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transmission",
            name="provenances",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transmission",
                to="quran.provenance",
            ),
        ),
    ]
