# Generated by Django 6.0.4 on 2026-07-15 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0008_alter_transmission_provenances"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transmission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2022-11-01 00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transmission",
            name="creator",
            field=models.ForeignKey(
                default="019f3bf8-0a9e-7aa4-a4f4-5f2b746bcd28",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transmission_creator",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transmission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
