# Generated by Django 5.1.7 on 2026-03-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0008_update_language_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recitation',
            name='duration',
        ),
    ]
