# Generated by Django 6.0.4 on 2026-07-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0009_transmission_created_at_transmission_creator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rasmolmushaf",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
