# Generated by Django 6.0.4 on 2026-07-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0010_rasmolmushaf_is_primary"),
    ]

    operations = [
        migrations.AddField(
            model_name="recitation",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
