# Generated by Django 6.0.4 on 2026-08-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0012_remove_word_text_wordtext"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rasmolmushaf",
            name="collector",
        ),
    ]
