# Generated by Django 6.0.4 on 2026-08-02 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0013_remove_rasmolmushaf_collector"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="rasmolmushaf",
            name="compiler",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compiler_rasmOlMushaf",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
