# Generated by Django 6.0.4 on 2026-08-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0014_alter_rasmolmushaf_compiler"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="surah",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="surah",
            name="rasm_ol_mushafs",
            field=models.ManyToManyField(to="quran.rasmolmushaf"),
        ),
        migrations.RemoveField(
            model_name="surah",
            name="rasm_ol_mushaf",
        ),
    ]
