# Generated by Django 6.0.4 on 2026-08-13 09:59

import core.expressions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0015_alter_surah_unique_together_surah_rasm_ol_mushafs_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RomSurahAyahs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=core.expressions.UUIDv7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ayah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rom_surah_ayahs_ayah",
                        to="quran.ayah",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rom_surah_ayahs_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rasm_ol_mushaf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rom_surah_ayahs_rom",
                        to="quran.rasmolmushaf",
                    ),
                ),
                (
                    "surah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rom_surah_ayahs_surah",
                        to="quran.surah",
                    ),
                ),
            ],
        ),
    ]
