# Generated by Django 6.0.4 on 2026-08-15 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran", "0016_romsurahayahs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surah",
            name="rasm_ol_mushafs",
        ),
        migrations.AddConstraint(
            model_name="romsurahayahs",
            constraint=models.UniqueConstraint(
                fields=("rasm_ol_mushaf", "surah", "ayah"),
                name="unique_mushaf_surah_ayah",
            ),
        ),
    ]
